### ISSUE TITLE
Is there clDice loss function for 3D image?

### ISSUE THREAD

**Issue by artzers** [dmitrysarov/clDice#2]
Hello, I want to find 3D clDice loss function for 3D tublar segmentation. As I know in some cldice-relate articles, 3D cldice loss has been applied but the corresponding codes are not published. Do you have any idea ? Thank you.

**Comment by dmitrysarov** [comment]
Good question. Sure you can by substituting pooling with 3d version and tweak minor parts. Contribution welcome!

**Comment by AlphaJia** [comment]
I tried the 3D clDicel loss, compared to other loss trained model, this clDice loss model achieved the highest recall and lowest precision. Interesting! it is most of true positive and false positive has been segmented out!

**Comment by AlphaJia** [comment]
I think the pred contour can be get using sobel operator

**Comment by jocpae** [comment]
Dear community, after acceptance in CVPR 2021 we now offer an official 2D and 3D implementation of cldice at https://github.com/jocpae/clDice . Thanks a lot to @dmitrysarov for implementing cldice :)

**Comment by dmitrysarov** [comment]
glad to help
